name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - qa
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python and dependencies
        uses: ./.github/actions/setup-python

      - name: Run tests
        run: |
          pytest tests/ -v
      
      - name: Test app import
        run: |
          python -c "import sys; sys.path.append('app'); import main; print('✅ App imports successfully')"